<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e6ffcbb0-43f8-4d57-a201-7926363c837a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\HRMS.Application\HRMS.Application.csproj" />
    <ProjectReference Include="..\HRMS.Infrastructure\HRMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
